### ISSUE TITLE
Feil Git commit hash vises i Github deployments

### ISSUE THREAD

**Issue by ahusby** [navikt/deployment#16]
Skriver hookd alltid nyeste commit hash til Github, selv om det var ikke-nyeste commit som ble deployet?

Jeg jobber med å sette opp build & deploy pipeline med Travis CI og deployer en dummy/hello-world applikasjon med den. En feature jeg må lage er tilbakerulling, dvs. at det må være mulig å prodsette en gammel versjon av applikasjonen, en versjon som har blitt prodsatt før. Jeg prøver å bruke TravisCI sitt web-GUI til å restarte et gammelt bygg. Det ser i skrivende stund ut til å fungere, bortsett fra feil info om deployment-en i Github.

Det gjelder oversikten over deployments i Github-repoet mitt: https://github.com/navikt/person-arkiv/deployments . Når jeg restarter nest nyeste bygg i Travis CI (nest nyeste commit til master-branchen) blir deployment-oversikten i Github oppdatert, men Git commit hash-en i de nye deployment-ene tilhører nyeste commit, ikke nest nyeste.

Det ser ut som at Docker-imaget som faktisk blir deployet er det riktige (nest nyeste commit). Basert på at jeg får Travis til å bruke commit hash-en som tag på navnet til Docker imageet. Ser Docker image tag-en ved å kjøre `kubectl describe ...` på den nye k8s pod-en.

Travis: https://travis-ci.com/navikt/person-arkiv/builds

Bildet viser at selv om ikke-nyeste commit a02d9e7 har blitt deployet på nytt så er det nyeste commit b2bce85 som er registrert som deployet:
![bilde](https://user-images.githubusercontent.com/12073037/59439007-c64d4480-8df4-11e9-8bc0-66ec9ada8cb9.png)

**Comment by davidsteinsland** [comment]
`ref` settes i deployment requesten man oppretter i GitHub, fra bygget ditt så setter du denne til `master` og ikke en sha:
```
deployment-cli deploy create --resource nais.yaml --appid 30124 --key githubApp_privateKey.pem --cluster dev-fss --repository $TRAVIS_REPO_SLUG  --ref $TRAVIS_BRANCH --team persondata --version 1.0.0
```
