### ISSUE TITLE
Feature request: Display k8s namespace in addition to cluster in Github Deployments activity log and 'active deployment' boxes

### ISSUE THREAD

**Issue by ahusby** [navikt/deployment#17]
The deployments overview in my Github repository has an activity log and above that two boxes for active deployments to the k8s clusters prod-fss and dev-fss. In my build & deploy pipeline I deploy the same version of my app twice to dev-fss - to two seperate k8s namespaces - and once to prod-fss (to the default namespace). This is because some people think that when deploying to production I need to first deploy to a verification environment, then to the production environment and then to a production-like environment. The view in Github does not display this. A solution would be to display the namespace name in addition to the cluster name in the activity log. The same goes for the boxes for active deployments, but I guess this implies that we will have more boxes: one for each combination of cluster and namespace.

The image shows that my one Travis CI build resulted in three deployments, out of which only two get the status "active". (See the commit hashes.) There should be three active deployments. Two of these deployments were to seperate k8s namespaces in the dev-fss cluster.

![bilde](https://user-images.githubusercontent.com/12073037/59443201-d74d8400-8dfb-11e9-9133-1db9980edd48.png)

**Comment by ambientsound** [comment]
Sorry, but we have little control over the activity log feature. This is Github's user interface and Github doesn't really know which namespace we use, or that we use Kubernetes at all in any case. We don't have any way to report back "extra" fields.

The only way to solve this issue would be to create a dashboard solution ourselves. @christeredvartsen anything to add here?

**Comment by Kyrremann** [comment]
Kunne vi ikke bare skrevet `cluster:namespace` i tittelen? I stedet for bare `cluster`?

**Comment by ambientsound** [comment]
@Kyrremann we don't have any control over the presentation layer here. At Github there is `environment` which here corresponds to the cluster in question.

Appreciate if you keep the discussion in English as well :)

**Comment by Kyrremann** [comment]
Why don't we just write `environment:namespace` instead of just `environment`?

**Comment by ahusby** [comment]
I https://github.com/navikt/circleci-nais-orb/issues/6 kjemper jeg stadig for at konseptet "miljø" (alias "environment") i Nais-kontekst skal være definert av kombinasjonen av clusternavn og namespacenavn. Dvs. at @Kyrremann sitt forslag ovenfor bør navngis "cluster:namespace".

**Comment by ahusby** [comment]
I diskusjon på Slack https://nav-it.slack.com/archives/CL3G3HZ37/p1563957258013100 kom vi fram til at namespace ikke skal brukes til å simulere miljøer. Det er en endring i forhold til det jeg så for meg da jeg opprettet denne issuen. Men det som forblir det samme er at mitt prosjekt kommer til å ha behov for å deploye flere versjoner av en app til samme cluster (dev-fss). I følge @TheUnnamedDude https://nav-it.slack.com/archives/CL3G3HZ37/p1563969992030200?thread_ts=1563957258.013100&cid=CL3G3HZ37  kan det løses ved å deploye samme app men med ulike appnavn i nais.yaml fila. Det har jeg fremdeles samme problem som opphavet til denne issuen: Jeg har flere aktive deploys til samme cluster fra samme Github repo, men visningen av Github deploys vil bare vise én av dem som aktiv. Nytt forslag til løsning blir da å skrive `environment:appname`. For å ta høyde for alt kan man skrive `environment:appname:namespace`.

**Comment by Kyrremann** [comment]
Closing this because we want people to use the `default` namespace, instead of spread their app out on different "miljø". Using different namespaces will also not be possible when a team moves over to the cloud/GCP, as every team gets their own namespace.
