### ISSUE TITLE
Mulighet for krypterte Kubernetes payload

### ISSUE THREAD

**Issue by TheUnnamedDude** [navikt/deployment#27]
Med dagens løsning vil Kubernetes payloadene lagres i klartekst i github APIet, for open-source prosjekter betyr dette at URL-er blir liggende tilgjengelig for scraping. Selv om disse ikke er sett på som Temmelig Hemmelig kan det være litt uheldig at de er så lett tilgjengelig da det beskriver noe av vår infrastruktur som ikke trenger å være offentlig informasjon.

Løsningen som har blitt diskutert er å ta i bruk JWE for å kryptere payloadet og eksponere et JWKS endepunkt som kan brukes av deployment-cli, dette gjør at det ikke blir noe mer kompleksitet for de som bruker deployment-cli.

En annen fremtidig mulighet med dette patternet er at vi kan kryptere secrets og opprette Kubernetes secrets via samme pipeline.

**Comment by androa** [comment]
Vi har yaml-filene liggende i git-repoene allerede. Hvor stort problem er dette egentlig?

**Comment by TheUnnamedDude** [comment]
Det er vel ikke ønskelig at dette skal ligge i public repo, men dere er ikke de eneste som har det. Jeg mener uansett at vi burde ha muligheten til å opprette en github deployment uten at informasjonen som beskriver infrastrukturen blir lekket

**Comment by androa** [comment]
Ikke ønskelig fra hvem? Den gjengse tolkning er vel at det er innafor.

**Comment by davidsteinsland** [comment]
👎 fra min side. Dette vil gjøre det temmelig vanskelig å bruke github deployments uten å måtte bruke deployment-cli. Dessuten har jeg vanskeligheter med å forstå hvor stor denne risikoen er. Jeg vil ikke påstå vi lekker noe spesiell informasjon om infrastrukturen i NAV, med unntak av hostnavn og urler på diverse tjenester.

**Comment by TheUnnamedDude** [comment]
Nå vet jeg ikke om mange team som _ikke_ bruker deployment-cli, det er ingen ting som stopper deg i å bruke andre verktøy for å bruke JWE og jeg ser heller ingen grunn til å ikke bruke deployment-cli. Dette har vært diskutert en del i plattformområde og vi har egentlig kommet frem til at det egentlig ikke er innafor at det ligger i det åpne, det er heller ingen grunn til at vi skal ha ting som beskriver nettverk/infrastruktur tilgjengelig i det åpne.

**Comment by jhrv** [comment]
Det er allerede temmelig vanskelig å bruke github deployments uten deployment-cli. 
Det er ingenting som hindrer folk fra å legge sin config i et public repo, og om det er innafor eller utafor trenger ikke vi å konkludere med. Det er flere som ikke er komfortable å legge denne configen åpent, og legger dette i egne private repos - og at vi da i neste steg tar den samme configen og eksponererer den via api.github.com/.../deployments er dårlig stil.

**Comment by androa** [comment]
Da er det mer nyttig at noen gjør en grundig ROS og konkluderer hvorvidt det er innafor å legge i public repos. Det er jo det enkleste. Det er dumt å gjøre ting vanskeligere enn det må være.

Viser det seg at det på ekte er problematisk så syntes jeg ikke yamlene hører hjemme i deployments-eventet i det hele tatt. Da bør de heller pushes på et eller annet artifact-store og refereres til. Via en sånn URL.

**Comment by TheUnnamedDude** [comment]
Er enig at vi burde finne ut hvor nødvendig det er og få en enighet i hvor sensitive URL-er etc egentlig er. Men en løsning via et annet artifact store er iallefall ikke noe lettere å implementere/bruke da man får enda et sett med credentials som må distribueres og et artifact store som må kjøpes inn og/eller vedlikeholdes

**Comment by davidsteinsland** [comment]
> Dette har vært diskutert en del i plattformområde og vi har egentlig kommet frem til at det egentlig ikke er innafor at det ligger i det åpne
Jeg syns det bør være opp til en risikoanalyse å vurdere dette. 
Hvor har det blitt diskutert? I #pig_deployment på Slack så har det ikke vært noe om dette tror jeg.  Det hadde iallfall vært fint å kunne ta del i diskusjonen før "noe ble bestemt".

Jeg syns ikke argumentet med at noen er ukomfortable eller at det er dårlig stil er godt nok. Enten så er dette informasjon vi ikke ønsker å eksponere ut av sikkerhetsmessige årsaker, eller så er det greit.

**Comment by tronghn** [comment]
Det er vel kanskje et større problem at vi ikke har noen klare føringer på hva som er innafor å legge ut i offentligheten som @androa nevner. Tror det kan ha litt å si for hva slags pattern eller standard vi skal ha for hvor vi skal lagre og hente config/yaml fra. Akkurat nå gjør jo teamene litt sånn som de vil, enten det ligger kodenært i repoene eller i egne private repoer - en slik endring som er foreslått her fordrer jo egentlig litt at man har en standard måte å gjøre ting på.

**Comment by davidsteinsland** [comment]
Kryptering vil ikke ha noe å si her, siden kommunikasjonen allerede er kryptert via TLS. Det som dog har noe å si er hvorvidt yaml er i public eller private repo. Kryptering vil ikke hjelpe om det er public repo, siden det uansett er lesbart med mindre man krypterer filene før man committer (men dette vil jo bare medføre ekstraarbeid og rom for menneskelig feil)

**Comment by TheUnnamedDude** [comment]
Et pattern som noen team bruker er at config blir lastet ned fra et privat repo under bygging, for så å legge inn URL-er i YAML. Disse URL-ene vil da ligge åpent tilgjengelig i deployment apiet.

**Comment by Kyrremann** [comment]
> Et pattern som noen team bruker er at config blir lastet ned fra et privat repo under bygging, for så å legge inn URL-er i YAML. Disse URL-ene vil da ligge åpent tilgjengelig i deployment apiet.

Kunne man ikke snudd deployen, deploye fra privat repo, og hente inn kode for appen?

**Comment by davidsteinsland** [comment]
> Disse URL-ene vil da ligge åpent tilgjengelig i deployment apiet.

Hva mener du med åpent? Kommunikasjonen er jo tls.

**Comment by jhrv** [comment]
> Hvor har det blitt diskutert? I #pig_deployment på Slack så har det ikke vært noe om dette tror jeg. Det hadde iallfall vært fint å kunne ta del i diskusjonen før "noe ble bestemt"

Enig i det, og tenker ingen har bestemt noe rundt dette. Vi kan gjerne diskutere dette og forsøke å lande et offisielt standpunkt på dette som det er konsensus på. 
Men pr i dag fins ikke dette, og nettopp derfor er det ufint at vi i praksis ikke tilbyr et alternativ for de som ikke ønsker å legge dette public. 

Med dette regimet i skala over tid, med så mange repos er det for lett å scrape alle deployments for alle repos og plukke ut `spec.env[]`.

Som @TheUnnamedDude  nevner, dette gjelder de som har config i privat repo og koden public.

**Comment by TheUnnamedDude** [comment]
https://api.github.com/repos/navikt/syfosmmottak/deployments

**Comment by TheUnnamedDude** [comment]
> > Et pattern som noen team bruker er at config blir lastet ned fra et privat repo under bygging, for så å legge inn URL-er i YAML. Disse URL-ene vil da ligge åpent tilgjengelig i deployment apiet.
> 
> Kunne man ikke snudd deployen, deploye fra privat repo, og hente inn kode for appen?

Problemet med dette er at sporbarheten i github deployment UIet blir helt borte og selve pipelinen blir en god del mer komplisert da man må trigge et bygg i et annet repo fra fra repoet koden ligger i

**Comment by TheUnnamedDude** [comment]
Burde også peke ut at det aldri har vært påtenkt at dette skal være påkrevd som tittelen tilsier

**Comment by davidsteinsland** [comment]
> https://api.github.com/repos/navikt/syfosmmottak/deployments

Jeg visste ikke at deployments events var tilgjengelige for hele verden, det stiller jo saken i et litt annet lys. 

Uansett hva som blir bestemt så burde det bli utført en risikoanalyse av dette – nemlig dette med at hostnavn og urler ligger åpent.

**Comment by eirslett** [comment]
Nok en gang diskuterer vi security by obscurity.
Det er en idiotisk innstilling til sikkerhet. Utviklere må ta eierskap til appene sine og bygge sikkerhet inn i produktet, i stedet for å lene seg tilbake og håpe på at et slør av hemmelighold rundt deployment vil være tilstrekkelig til å kunne sove godt om natta.

Noen utviklere er ukomfortable med å legge triviell config ut public. Jeg er ukomfortabel med å jobbe med utviklere som tenker at _det_ er måten vi skal løse sikkerhet på. Hvis appen din har god sikkerhet (og kanskje allerede er open source uansett), så må configen tåle dagens lys.

:+1: for å la denne typen config ligge åpent. La oss bruke tiden på å prioritere sikkerhetstiltak som gir mer reell effekt, enn på å bygge ekstra kompleksitet rundt å kryptere slik config.

**Comment by TheUnnamedDude** [comment]
Problemet ligger ikke i de appene vi ønsker at skal ligge i det åpne, det er alle applikasjonene som ikke ligger i det åpne. Det at configen ligger i åpne repositories gir også null verdi da det eneste det beskriver er hvordan infrastrukturen er satt opp. Det er heller ikke security through obscurity, ingen burde basere sikkerheten sin på at URL-er ikke er tilgjengelig. Det blir som å si at man skal kunne legge ut passord i et åpent repository fordi man ikke skal ha tilgang til å nå en database i første omgang.

**Comment by eirslett** [comment]
Det gir verdi at det ligger i åpne repo. For det første så setter det forventninger til utviklere om at det ligger åpent. For det andre så slipper vi å bruke tid på kompleksiteten med å holde det lukket (JWE, JWKS osv.)

> kan det være litt uheldig at de er så lett tilgjengelig da det beskriver noe av vår infrastruktur som ikke trenger å være offentlig informasjon.

> Det er heller ikke security through obscurity, ingen burde basere sikkerheten sin på at URL-er ikke er tilgjengelig.

Men hva vil du kalle det da, om det ikke er security by obscurity?

> Det blir som å si at man skal kunne legge ut passord i et åpent repository fordi man ikke skal ha tilgang til å nå en database i første omgang.

Passord er det motsatte, fordi hele poenget med passord er nettopp at de skal være secret.

**Comment by jhrv** [comment]
Vi snakker ikke om samme ting her @eirslett. 
Ingen hevder at det at noen kjenner til en URL isolert sett er en sikkerhetsrisiko fordi noen vet om den URLen. Det vi snakker om er at dersom man drar det patternet her ut i stort, vil all miljøspesifikk informasjon for alle applikasjoner i NAV, database urler, sentrale infra tjenester, køer og endepunkter ligge åpent for absolutt alle. I scenarioet der man er en angriper som ønsker å skaffe seg oversikt over NAVs infrastruktur og danne seg et bilde av det, tilbyr vi i praksis all denne infoen strukturert og lett tilgjengelig via api.github.com. Det syns jeg ikke vi skal.

**Comment by eirslett** [comment]
Jeg er ganske sikker på at vi snakker om akkurat samme ting.
Vi er bare uenige i hvor sensitivt det skal være.

**Comment by androa** [comment]
X-post fra den parallele tråden på Slack: Dette er jo Service Discovery. Det finnes ørtiseks forskjellige løsninger på dette problemet. SOURCINGSTRATEGIEN FOLKENS. La oss da plukke noe ferdig hyllevare for et ferdig løst problem.

**Comment by TheUnnamedDude** [comment]
Personlig mener jeg det ikke er veldig sensitivt, informasjonen får man relativt raskt med enumerering og litt prøving og feiling. Argumentet har vel vært at det er lettere å finne ut at det har vært en breach under enumerering? Jeg ser heller ingen grunn til at det skal være åpent og tilgjengelig annet enn kompleksiteten i JWE/JWKS, men dette er ting en utvikler burde kjenne uansett for å sikre de samme URLene.

**Comment by ambientsound** [comment]
Krypterte payloads vil gi oss muligheten til å deploye secrets og annen sensitiv konfigurasjon på samme måte som vi deployer applikasjonen. Å ikke kunne deploye secrets er en dealbreaker for at NAIS-komponenter skal deployes via NAIS deploy. I tillegg gjelder det samme for applikasjoner som vil ta i bruk native secrets.

Støtter @jhrv sitt argument om at å legge ut topologien til applikasjonsinfrastrukturen *vil* gjøre det lettere for potensielle angripere å kartlegge og planlegge angrep mot NAV. Sikkerhet gjør man lag for lag, og dette vil hjelpe på. Vi *baserer* oss ikke på security by obscurity, men litt obscurity gjør å cracke sikkerheten vår til et mindre oppnåelig mål.

@androa har et poeng med at å kreve kryptering vil gjøre det vanskeligere å bruke cURL. For å opprettholde dagens enkelhet kan man da støtte både krypterte og plaintext payloads for de med spesielle behov.

**Comment by Kyrremann** [comment]
Vi ser på å snu dette problemet, ved at vi kun melder tilbake til Github at en deployment har blitt gjort. Altså at deployment-cli snakker med hookd direkte (uten å gå via github deployment).

Se ADR i pig-deployment: https://github.com/navikt/pig/blob/master/deployment/adr/003-direct-deployment.md

**Comment by ambientsound** [comment]
Som @Kyrremann nevner, løser vi dette på en annen måte. Lukker derfor issue.
