### ISSUE TITLE
Fikse din ip har ikke tilgang til denne tjenesten.

### ISSUE THREAD

**Issue by Kyrremann** [navikt/deployment#30]
Kunne vi fikset feilen med?
> Din ip 172.31.2.109 har ikke tilgang til denne tjenesten.

**Comment by ambientsound** [comment]
Fikset

**Comment by Kyrremann** [comment]
Kolól, hva var løsningen?

**Comment by ambientsound** [comment]
Åpnet for en større IP-range og fjernet sjekken for IP (som ikke fungerte i utgangspunktet, derav feilmeldingen).
