### ISSUE TITLE
Fjerne støtte for default for GCP

### ISSUE THREAD

**Issue by Kyrremann** [navikt/deployment#32]
GCP støtter ikke namespace `default`. Man burde få feilmelding hvis man prøver å deploye til det namespacet.

Ulempen er at dette er definert i `nais.yaml`.

**Comment by Kyrremann** [comment]
Snakket med @ambientsound om dette. Vi er enige om at vi ønsker at dette skal rapporteres som feil fra Kubernetes, og at du ikke vil få en feil fra pipeline/deployment-cli.

Så forhåpentligvis blir dette løst når GCP er mer GA, hvor namespace `default` ikke vil kunne bli brukt slik som man kan nå. Regner med at dette blir løst med RBAC.

**Comment by ambientsound** [comment]
Legge inn denne issuen i et annet prosjekt?
