### ISSUE TITLE
Robust handling of deployment statuses

### ISSUE THREAD

**Issue by ambientsound** [navikt/deployment#8]
Mark Kafka messages as consumed only when Github says that the deployment status was successfully created. Additionally, consider retries when producing these messages on the Kafka topic.

**Comment by ambientsound** [comment]
Retries added in 2428fff4 and 0683774b

**Comment by Kyrremann** [comment]
Is this done?

**Comment by ambientsound** [comment]
Sort of. There is a case where deployment messages might be lost if hookd is restarted after a `201 Created`, but before the message is produced on the Kafka topic. This can happen if Kafka is unavailable for any reason.

However, messages that failed are put on a retry queue, so as long as hookd isn't restarted, everything should eventually resolve itself.

The consequences of lost messages are unfulfilled deployments, which is not a disaster. I would say we can close this issue :)
